line-length = 120
indent-width = 4

[lint]
select = ["E","F","I","B","UP","S","C4","SIM","N","RUF"]
ignore = ["S101"]

[lint.isort]
combine-as-imports = true
known-first-party = ["backend", "diff_worker"]
