version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    environment:
      ARTIFACTORY_URL: ${ARTIFACTORY_URL:-}
      ARTIFACTORY_TOKEN: ${ARTIFACTORY_TOKEN:-}
      STAGING_REPO: ${STAGING_REPO:-npm-staging}
      PROD_REPO: ${PROD_REPO:-npm-prod}
      QUARANTINE_REPO: ${QUARANTINE_REPO:-npm-quarantine}
      LLM_PROVIDER: ${LLM_PROVIDER:-openai}
      LLM_API_KEY: ${LLM_API_KEY:-}
      POLICY_FILE: ${POLICY_FILE:-policy.yaml}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    environment:
      ARTIFACTORY_URL: ${ARTIFACTORY_URL:-}
      ARTIFACTORY_TOKEN: ${ARTIFACTORY_TOKEN:-}
      STAGING_REPO: ${STAGING_REPO:-npm-staging}
      PROD_REPO: ${PROD_REPO:-npm-prod}
      QUARANTINE_REPO: ${QUARANTINE_REPO:-npm-quarantine}
      LLM_PROVIDER: ${LLM_PROVIDER:-openai}
      LLM_API_KEY: ${LLM_API_KEY:-}
      POLICY_FILE: ${POLICY_FILE:-policy.yaml}
    depends_on:
      - api

networks:
  default:
    name: diffguard-net
